{% set name = "demcmc" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/demcmc-{{ version }}.tar.gz
  sha256: 2cf7f99334cb5c1a55fb3eec21b23a0ec28c2f66410bbec353c6ab3c4ddaf6f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - astropy
    - emcee
    - matplotlib-base
    - netcdf4
    - numpy
    - pooch
    - xarray

test:
  imports:
    - demcmc
  commands:
    - pip check
    - tox
  requires:
    - pip
    - tox

about:
  summary: Differential Emission Measure calculations using Monte Carlo methods.
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://demcmc.readthedocs.io
  dev_url: https://github.com/dstansby/demcmc

extra:
  recipe-maintainers:
    - dstansby
