{% set name = "demcmc" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/demcmc-{{ version }}.tar.gz
  sha256: e64eda8ad27dbf4f7f5b21f6607e7f8f4071d22e4e4c4bf0b6be1718259a8cb9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - astropy
    - emcee
    - matplotlib-base
    - netcdf4
    - numpy
    - pooch
    - xarray

test:
  imports:
    - demcmc
  commands:
    - pip check
    - tox
  requires:
    - pip
    - tox

about:
  summary: Differential Emission Measure calculations using Monte Carlo methods.
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://demcmc.readthedocs.io
  dev_url: https://github.com/dstansby/demcmc

extra:
  recipe-maintainers:
    - dstansby
